_target_: leaf.inference.Predictor

# This defines which module will be run 
module_params:
  symptoms_det: True
  symptoms_seg: True
  organs: False
  focus: False

# This defines paramters for symptoms detection
symptoms_det_params:
  patch_sz: [2048, 8192]
  keypoints_thresh: 0.212
  use_gpu: True
  model_name: 'latest'

# This defines paramters for symptoms segmentation
symptoms_seg_params:
  patch_sz: [2048, 8192]
  input_scaling: 0.5
  use_gpu: True
  model_name: 'tracking_latest'
